INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (1, 'opena3xx.a320.pedestal.mcdu.pilot', 'MCDU Device (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (2, 'opena3xx.a320.pedestal.mcdu-.copilot', 'MCDU Device (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (3, 'opena3xx.a320.glareshield.fcu.shared', 'FCU Device (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (4, 'opena3xx.a320.glareshield.illumination-control.pilot', 'Illumination Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (5, 'opena3xx.a320.glareshield.illumination-control.copilot', 'Illumination Panel (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (6, 'opena3xx.a320.glareshield.efis.pilot', 'EFIS Device (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (7, 'opena3xx.a320.glareshield.efis.copilot', 'EFIS Device (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (8, 'opena3xx.a320.glareshield.terrain-indicator-control.pilot', 'Terrain Indicator (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (9, 'opena3xx.a320.glareshield.terrain-indicator-control.copilot', 'Terrain Indicator (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (10, 'opena3xx.a320.glareshield.landing-gear-control.shared', 'Landing Gear (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (11, 'opena3xx.a320.glareshield.chrono-control.shared', 'Chrono (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (12, 'opena3xx.a320.glareshield.brakes-control.shared', 'Brakes Control Unit (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (13, 'opena3xx.a320.glareshield.autoland-control.pilot', 'Autoland (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (14, 'opena3xx.a320.glareshield.autoland-control.copilot', 'Autoland (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (15, 'opena3xx.a320.glareshield.accu-press.shared', 'Accu-Press Gauge (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (16, 'opena3xx.a320.pedestal.start-engines-control.shared', 'Start Engines Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (17, 'opena3xx.a320.pedestal.atc-control.shared', 'ATC Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (18, 'opena3xx.a320.pedestal.audio-control.pilot', 'Audio Control Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (19, 'opena3xx.a320.pedestal.audio-control.copilot', 'Audio Control Panel (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (20, 'opena3xx.a320.pedestal.lighting-control.pilot', 'Pedestal Lighting Control Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (21, 'opena3xx.a320.pedestal.cockpit-door-control.shared', 'Cockpit Door Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (22, 'opena3xx.a320.pedestal.flaps.shared', 'Flaps Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (23, 'opena3xx.a320.pedestal.lighting-control.copilot', 'Pedestal Lighting Control Panel (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (24, 'opena3xx.a320.pedestal.ecam-control.shared', 'ECAM Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (25, 'opena3xx.a320.pedestal.radar-control.shared', 'Radar Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (26, 'opena3xx.a320.pedestal.radio-control.pilot', 'Radio Control Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (27, 'opena3xx.a320.pedestal.radio-control.copilot', 'Radio Control Panel (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (28, 'opena3xx.a320.pedestal.ruddertrim-control.shared', 'Rudder Trim Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (29, 'opena3xx.a320.pedestal.spoilers-control.shared', 'Spoilers Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (30, 'opena3xx.a320.pedestal.display-switching-control.shared', 'Display Switching Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (31, 'opena3xx.a320.overhead.adirs-control.shared', 'ADIRS Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (32, 'opena3xx.a320.overhead.air-condition-control.shared', 'Air Conditioning Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (33, 'opena3xx.a320.overhead.anti-ice-control.shared', 'Anti Ice Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (34, 'opena3xx.a320.overhead.cabin-pressure-control.shared', 'Cabin Pressure Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (35, 'opena3xx.a320.overhead.external-lighting-control.shared', 'External Lighting Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (36, 'opena3xx.a320.overhead.apu-control.shared', 'APU Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (37, 'opena3xx.a320.overhead.internal-lighting-control.shared', 'Internal Lighting Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (38, 'opena3xx.a320.overhead.signs-control.shared', 'Signs Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (39, 'opena3xx.a320.overhead.electrical-control.shared', 'Electrical Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (40, 'opena3xx.a320.overhead.engines-fire-control.shared', 'Engines Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (41, 'opena3xx.a320.overhead.fuel-control.shared', 'Fuel Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (42, 'opena3xx.a320.overhead.hydraulic-pumps-control.shared', 'Hydraulic Pumps Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (43, 'opena3xx.a320.overhead.flight-control.pilot', 'Flight Control Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (44, 'opena3xx.a320.overhead.flight-control.copilot', 'Flight Control Panel (CoPilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (45, 'opena3xx.a320.overhead.evac-control.shared', 'Evacuation Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (46, 'opena3xx.a320.overhead.emergency-elec-power-control.shared', 'Emergency Electrical Power Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (47, 'opena3xx.a320.overhead.gpws-control.shared', 'GPWS Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (48, 'opena3xx.a320.overhead.recorder-control.shared', 'Recorder Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (49, 'opena3xx.a320.overhead.oxygen-control.shared', 'Oxcygen Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (50, 'opena3xx.a320.overhead.calls-control.shared', 'Calls Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (51, 'opena3xx.a320.overhead.wind-screen-control.pilot', 'Wind Screen Control Panel (Pilot)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (52, 'opena3xx.a320.overhead.cargo-vent-control.shared', 'Cargo Vent Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (53, 'opena3xx.a320.overhead.cargo-smoke-control.shared', 'Cargo Smoke Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (54, 'opena3xx.a320.overhead.ventilation-control.shared', 'Ventilation Control Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (55, 'opena3xx.a320.overhead.engines-master-control.shared', 'Engine Master Controls Panel (Shared)');
INSERT INTO HardwareComponents (Id, InternalId, Name) VALUES (56, 'opena3xx.a320.overhead.wind-screen-control.copilot', 'Wind Screen Control Panel (CoPilot)');